accounts/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', 'accounts.views.logout_user', name='logout'),
)

auctions/urls.py
from django.conf.urls import patterns, url

from .views import AuctionList, AuctionCreate, AuctionUpdate, AuctionDelete, AuctionDetail, BidView, AuctionTaggedList


urlpatterns = patterns('',
    url(r'auctions/$', AuctionList.as_view(), name='auction_list'),

    url(r'^auction/add/(?P<slug>[^\.]+)/$', AuctionCreate.as_view(), name='auction_add'),
    url(r'^auction/edit/(?P<slug>[^\.]+)/$', AuctionUpdate.as_view(), name='auction_edit'),
    url(r'^auction/delete/(?P<slug>[^\.]+)/$', AuctionDelete.as_view(), name='auction_delete'),

    url(r'^auction/bid/(?P<slug>[^\.]+)/$', BidView.as_view(), name='bid'),

    url(r'^auction/(?P<slug>[^\.]+)/$', AuctionDetail.as_view(), name='auction_detail'),

    url(r'^auctions/tag/(?P<tag>[^\.]+)/$', AuctionTaggedList.as_view(), name='tag_list'),
)

augeo/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from rest_framework import routers

from core.api import ArtworkViewSet
from auctions.api import AuctionViewSet

import core.urls as core
import auctions.urls as auctions
import social.apps.django_app.urls as social
import profiles.urls as profiles
import events.urls as events
import rest_framework.urls as rest_framework

admin.autodiscover()


# Routers provide an easy way of automatically determining the URL conf
router = routers.DefaultRouter()
router.register(r'artworks', ArtworkViewSet, base_name='artwork')
router.register(r'auctions', AuctionViewSet, base_name='auction')


urlpatterns = patterns('',
    url(r'^api/v1/', include(router.urls)),

    url(r'^admin/', include(admin.site.urls)),
    url(r'', include(core, namespace='core')),
    url(r'', include(auctions, namespace='auctions')),
    url('', include(social, namespace='social')),
    url(r'', include(profiles, namespace='profiles')),
    url(r'', include(events, namespace='events')),

    url(r'^api-auth/', include(rest_framework, namespace='rest_framework')),
    url(r'^api-token-auth/', 'rest_framework.authtoken.views.obtain_auth_token')
)

core/urls.py
from django.conf.urls import patterns, url

from .views import ArtworkList, ArtworkCreate, ArtworkUpdate, ArtworkDelete, ArtworkDetail, ContactFormView, ArtworkTaggedList

urlpatterns = patterns('',
    url(r'^$', ArtworkList.as_view(), name='home'),
    url(r'contact/$', ContactFormView.as_view(), name='contact'),
    url(r'artwork/add/$', ArtworkCreate.as_view(), name='artwork_add'),
    url(r'^artwork/edit/(?P<slug>[^\.]+)/$', ArtworkUpdate.as_view(), name='artwork_edit'),
    url(r'^artwork/delete/(?P<slug>[^\.]+)/$', ArtworkDelete.as_view(), name='artwork_delete'),
    url(r'^artwork/(?P<slug>[^\.]+)/$', ArtworkDetail.as_view(), name='artwork_detail'),
    url(r'^artworks/tag/(?P<tag>[^\.]+)/$', ArtworkTaggedList.as_view(), name='tag_list'),
)

events/urls.py
from django.conf.urls import patterns, url

from .views import ping

urlpatterns = patterns('',
    url(r'ping/$', ping, name='ping'),
)

auctions/models.py
from datetime import time
from decimal import Decimal

from django.core.cache import cache
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_delete
from django.dispatch import receiver

from south.modelsinspector import add_introspection_rules

from core.models import Artwork
from events.views import pubnub
from .utils import get_current_time




class CurrencyField(models.DecimalField):
    __metaclass__ = models.SubfieldBase

    def __init__(self, verbose_name=None, name=None, **kwargs):
        decimal_places = kwargs.pop('decimal_places', 2)
        max_digits = kwargs.pop('max_digits', 10)

        super(CurrencyField, self). __init__(
            verbose_name=verbose_name, name=name, max_digits=max_digits,
            decimal_places=decimal_places, **kwargs)

    def to_python(self, value):
        try:
            return super(CurrencyField, self).to_python(value).quantize(Decimal("0.01"))
        except AttributeError:
            return None


add_introspection_rules([
    (
            [CurrencyField],
            [],
            {
                "decimal_places": ["decimal_places", {"default": "2"}],
                "max_digits": ["max_digits", {"default": "10"}],
            },
    ), ], ['^application\.fields\.CurrencyField'])




class AuctionManager(models.Manager):
    def get_auction(self, slug):
        key = "auction:%s" % slug
        auction = cache.get(key)
        if not auction:
            try:
                auction = Auction.objects.select_related().get(lot__slug=slug)
            except ObjectDoesNotExist:
                return None
            cache.add(key, auction)
        return auction


class Auction(models.Model):
    ENGLISH_AUCTION = 1
    REALTIME_ENGLISH_AUCTION = 2
    FIRST_PRICE_SEALED_BID_AUCTION = 3
    AUCTION_TYPES = (
        (ENGLISH_AUCTION, 'English auction'),
        (REALTIME_ENGLISH_AUCTION, 'Real-time English auction'),
        (FIRST_PRICE_SEALED_BID_AUCTION, 'First-price sealed-bid auction'),
    )

    STATUS_READY = 1
    STATUS_ACTIVE = 2
    STATUS_FINISHED = 3
    STATUS_SETTLED = 4
    STATUS_DISABLED = 5
    AUCTION_STATUSES = (
        (STATUS_READY, 'Ready'),
        (STATUS_ACTIVE, 'Active'),
        (STATUS_FINISHED, 'Finished'),
        (STATUS_SETTLED, 'Settled'),
        (STATUS_DISABLED, 'Disabled'),
    )

    lot = models.OneToOneField(Artwork, verbose_name="Lot", blank=False)
    type = models.PositiveSmallIntegerField("Auction type", blank=False, choices=AUCTION_TYPES, default=ENGLISH_AUCTION)
    status = models.PositiveSmallIntegerField("Status", blank=False, choices=AUCTION_STATUSES, default=STATUS_READY, db_index=True)
    start = models.DateTimeField("Auction start", blank=False, db_index=True)
    end = models.DateTimeField("Auction end", blank=False, db_index=True)
    reserve_price = CurrencyField("Reserve price", blank=True)
    reserve_price_posted = models.BooleanField("Is reserve price posted?", default=False)
    minimum_bid = CurrencyField("Minimum bid", blank=True)
    bid_increment = CurrencyField("Minimum bid increment", blank=True)
    realtime_increment = models.TimeField("Auction dynamic closing time increment", default=time(0, 10, 0))
    highest_bid = CurrencyField("Highest bid", blank=True)
    total_bids = models.PositiveIntegerField("Total bids", default=0)
    created = models.DateTimeField("Created", auto_now_add=True)
    modified = models.DateTimeField("Modified", auto_now=True)

    objects = AuctionManager()

    class Meta:
        verbose_name = 'Auction'
        verbose_name_plural = 'Auctions'

    def save(self, *args, **kwargs):
        super(Auction, self).save(*args, **kwargs)
        key = "auction:%s" % self.lot.slug
        cache.set(key, self)

    def get_absolute_url(self):
        return reverse('auctions:auction_detail', kwargs={'slug': self.lot.slug})

    @property
    def is_locked(self):
        """
        Bid baskets check this method to find out if a bid can be manipulated.
        """
        now = get_current_time()
        if self.end <= now:
            return True
        return False

    def __unicode__(self):
        return self.lot.title


@receiver(pre_delete, sender=Auction, dispatch_uid='auction_pre_delete')
def auction_pre_delete(sender, instance, using, **kwargs):
    key = "auction:%s" % instance.lot.slug
    cache.delete(key)



class BidBasketManager(models.Manager):
    def get_basket(self, user):
        key = "basket:%s" % user.username
        basket = cache.get(key)
        if not basket:
            try:
                basket = BidBasket.objects.get(bidder=user)
            except ObjectDoesNotExist:
                return None
            cache.add(key, basket)
        return basket


class BidBasket(models.Model):
    """
    This models functions similarly to a shopping cart, except it expects a logged in user.
    """
    bidder = models.OneToOneField(User, verbose_name="Bidder", blank=False)
    created = models.DateTimeField('Created', auto_now_add=True)
    modified = models.DateTimeField('Modified', auto_now=True)

    objects = BidBasketManager()

    class Meta:
        verbose_name = 'Bid basket'
        verbose_name_plural = 'Bid baskets'

    def save(self, *args, **kwargs):
        super(BidBasket, self).save(*args, **kwargs)
        key = "basket:%s" % self.bidder.username
        cache.set(key, self)

    def add_bid(self, auction, amount):
        if auction.is_locked:
            return False

        try:
            amount = Decimal(amount)
        except Exception:
            return False

        highest_bid = Bid.objects.get_highest_bid(auction)
        if amount <= highest_bid:
            return False

        bid, created = Bid.objects.get_or_create(bid_basket=self, auction=auction, amount=amount)
        if bid:
            bid.save()
            self.save()

            amount_text = str(amount.quantize(Decimal("0.01")))

            pubnub.publish({
                'channel': auction.lot.slug,
                'message': {
                    'text': 'New bid!',
                    'amount': amount_text
                }
            })

            pubnub.publish({
                'channel': auction.lot.publisher.username,
                'message': {
                    'text': 'New bid %s on <strong>"%s"</strong>' % (amount_text, auction),
                }
            })
        return bid

    def update_bid(self, auction, amount):
        """
        Update amount of bid. Delete bid if amount is 0.
        """
        try:
            amount = Decimal(amount)
        except Exception, e:
            amount = Decimal('0')

        bid = Bid.objects.get(bid_busket=self, auction=auction)
        if not bid.is_locked():
            if amount == 0:
                bid.delete()
            else:
                bid.amount = amount
                bid.save()
            self.save()
        return bid

    def delete_bid(self, auction):
        """
        Delete a single item from bid basket.
        """
        bid = Bid.objects.get(bid_busket=self, auction=auction)
        if not bid.is_locked():
            bid.delete()
            self.save()
        return bid

    def empty(self):
        """
        Remove all bids from bid basket.
        """
        Bid.objects.filter(bid_busket=self, is_locked=False).delete()
        self.save()

    def total_bids(self):
        """
        Returns total bids in basket.
        """
        return Bid.objects.filter(bid_busket=self).count()




class BidManager(models.Manager):
    def get_highest_bid(self, auction):
        key = "highest_bid:%s" % auction.lot.slug
        highest_bid = cache.get(key)
        if not highest_bid:
            try:
                highest_bid = Bid.objects.filter(auction=auction).aggregate(models.Max('amount'))['amount__max']
            except ObjectDoesNotExist:
                return None
            cache.add(key, highest_bid)
        return highest_bid


class Bid(models.Model):
    auction = models.ForeignKey(Auction, verbose_name="Auction", blank=False, related_name='bids')
    bid_basket = models.ForeignKey(BidBasket, verbose_name="Bid basket", blank=False, related_name='bids')
    amount = CurrencyField('Amount', blank=False, db_index=True)
    created = models.DateTimeField('Created', auto_now_add=True)

    objects = BidManager()

    class Meta:
        verbose_name = 'Bid'
        verbose_name_plural = 'Bids'

    def save(self, *args, **kwargs):
        super(Bid, self).save(*args, **kwargs)
        key = "highest_bid:%s" % self.auction.lot.slug
        cache.set(key, self.amount)

auctions/forms.py
import floppyforms as forms

from .models import Auction, Bid


class AuctionForm(forms.ModelForm):
    class Meta:
        model = Auction
        fields = ('start', 'end',)
        widgets = {
            'start': forms.DateTimeInput(attrs={'placeholder': 'Date & Time'}),
            'end': forms.DateTimeInput(attrs={'placeholder': 'Date & Time'}),
        }


class BidForm(forms.ModelForm):
    class Meta:
        model = Bid
        fields = ('amount',)

auctions/views.py
from decimal import Decimal
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, DetailView, RedirectView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from braces.views import LoginRequiredMixin

from core.models import Artwork
from .models import Auction, BidBasket, Bid
from .forms import AuctionForm


class AuctionTaggedList(ListView):
    paginate_by = 50

    def get_queryset(self):
        tag = self.kwargs['tag']
        artworks = Artwork.objects.values_list('id', flat=True).filter(tags__name__in=[tag])
        auctions = Auction.objects.select_related().filter(lot__in=artworks)
        return auctions


class AuctionList(ListView):
    paginate_by = 50

    def get_queryset(self):
        return Auction.objects.select_related()


class AuctionCreate(LoginRequiredMixin, CreateView):
    model = Auction
    template_name = 'auction_add.html'
    form_class = AuctionForm

    def get_context_data(self, **kwargs):
        context = super(AuctionCreate, self).get_context_data(**kwargs)
        context['lot'] = Artwork.objects.get_artwork(self.kwargs['slug'])
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        form.instance.lot = context['lot']
        self.object = form.save()
        return HttpResponseRedirect(self.object.get_absolute_url())

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))


class AuctionDetail(DetailView):
    model = Auction

    def get_object(self, queryset=None):
        return Auction.objects.get_auction(self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(AuctionDetail, self).get_context_data(**kwargs)
        lot = Artwork.objects.get_artwork(self.kwargs['slug'])
        context['lot'] = lot
        context['photo'] = lot.get_photo()
        context['auction_channel'] = self.kwargs['slug']
        bid = Bid.objects.get_highest_bid(self.object)
        if bid:
            context['bid'] = bid
        return context


class AuctionUpdate(LoginRequiredMixin, UpdateView):
    model = Auction
    form_class = AuctionForm
    template_name = 'auction_edit.html'

    def get_object(self, queryset=None):
        return Auction.objects.get_auction(self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(AuctionUpdate, self).get_context_data(**kwargs)
        context['lot'] = Artwork.objects.get_artwork(self.kwargs['slug'])
        return context

    def get_success_url(self):
        return reverse_lazy('auctions:auction_detail', kwargs={'slug': self.object.lot.slug})


class AuctionDelete(LoginRequiredMixin, DeleteView):
    model = Auction
    success_url = reverse_lazy('auctions:auction_list')

    def get_object(self, queryset=None):
        return Auction.objects.get_auction(self.kwargs['slug'])




class BidView(LoginRequiredMixin, RedirectView):

    def post(self, request, *args, **kwargs):
        user = request.user
        basket, created = BidBasket.objects.get_or_create(bidder=user)
        if basket:
            amount = request.POST['amount']
            if Decimal(amount):
                auction = Auction.objects.get_auction(kwargs['slug'])
                bid = basket.add_bid(auction, amount)
        return super(BidView, self).post(request, *args, **kwargs)

    def get_redirect_url(self, slug):
        return reverse_lazy('auctions:auction_detail', kwargs={'slug': slug})

templates/auctions/auction_add.html
{% extends "base.html" %}
{% load staticfiles %}
{% load cloudinary %}
{% load crispy_forms_tags %}


{% block css %}
    {{ block.super }}
    <link href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" rel="stylesheet">
    <link href="{% static "css/jquery-ui-timepicker-addon.css" %}" rel="stylesheet">
{% endblock css %}


{% block navbar %}
    <ul class="nav navbar-nav">
        <li><a href={% url 'core:home' %}>Artworks</a></li>
        <li class="active"><a href={% url 'auctions:auction_list' %}>Auctions</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
        <li><a href={% url 'events:ping' %}>Ping</a></li>
    </ul>
    <div class="nav navbar-btn navbar-right btn-group">
        {% if user.is_authenticated %}
            <a class="btn btn-primary" href="{% url 'core:artwork_add' %}">Add Artwork</a>
            <a class="btn btn-default" href={% url 'profiles:logout' %}>Logout</a>
        {% else %}
            <a data-toggle="modal" href="#loginModal" class="btn btn-default">Log in</a>
            <a href="#" class="btn btn-default">Sign up</a>
        {% endif %}
    </div>
{% endblock navbar %}


{% block content %}
    <form role="form" action="{% url "auctions:auction_add" slug=lot.slug %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Put on auction</button>
    </form>
{% endblock content %}


{% block js %}
    {{ block.super }}
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script src="{% static "js/jquery-ui-timepicker-addon.js" %}"></script>
    <script>
        $(function () {
            $("#id_start").datetimepicker({
                timeFormat: "HH:mm"
            });
            $("#id_end").datetimepicker({
                timeFormat: "HH:mm"
            });
        });
    </script>
{% endblock js %}

templates/auctions/auction_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load cloudinary %}


{% block css %}
    {{ block.super }}
    <link href="{% static "css/bootstrap-lightbox.min.css" %}" rel="stylesheet">
{% endblock css %}


{% block navbar %}
    <ul class="nav navbar-nav">
        <li><a href={% url 'core:home' %}>Artworks</a></li>
        <li class="active"><a href={% url 'auctions:auction_list' %}>Auctions</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
        <li><a href={% url 'events:ping' %}>Ping</a></li>
    </ul>
    <div class="nav navbar-btn navbar-right btn-group">
        {% if user.is_authenticated %}
            <a class="btn btn-primary" href="{% url 'core:artwork_add' %}">Add Artwork</a>
            <a class="btn btn-default" href={% url 'profiles:logout' %}>Logout</a>
        {% else %}
            <a data-toggle="modal" href="#loginModal" class="btn btn-default">Log in</a>
            <a href="#" class="btn btn-default">Sign up</a>
        {% endif %}
    </div>
{% endblock navbar %}


{% block content %}

    <div class="page-header">
        <h1>
            <p>{{ lot.title }}</p>

            <p>
                <small>{{ lot.artist }}</small>
            </p>
        </h1>
    </div>

    <div class="row">
        <div class="col-md-10">
            <a data-toggle="lightbox" href="#imageLightbox">
                {% cloudinary photo.image width=800 height=800 crop="fit" class="img-responsive img-rounded" %}
            </a>
        </div>
        <div class="col-md-2">
            {% if user.is_authenticated %}

                {% if bid %}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">Current bid</h3>
                        </div>
                        <div id="current-bid-container" class="panel-body">
                            {{ bid }}
                        </div>
                    </div>
                {% endif %}

                {% if lot.publisher == user %}
                    <div class="btn-group-vertical">
                        <a href="{% url 'auctions:auction_edit' slug=lot.slug %}"
                           class="btn btn-warning"><span class="glyphicon glyphicon-edit"></span> Edit
                            auction</a>
                        <a data-toggle="modal" href="#deleteModal" class="btn btn-danger"><span
                                class="glyphicon glyphicon-trash"></span> Delete</a>
                    </div>
                    {% include "includes/_auction_delete_confirmation.html" %}
                {% else %}
                    <a data-toggle="modal" href="#bidModal" class="btn btn-success"><span
                            class="glyphicon glyphicon-usd"></span> Bid</a>
                    {% include "includes/_bid_modal_form.html" %}
                {% endif %}
            {% endif %}
        </div>
    </div>

    <div id="imageLightbox" class="lightbox fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class='lightbox-dialog'>
            <div class='lightbox-content'>
                {% cloudinary photo.image %}
                <div class='lightbox-caption'>
                    {{ lot.title }}
                </div>
            </div>
        </div>
    </div>

    <p>
        <small>Published {{ lot.published|date }} by {{ lot.publisher }}</small>
    </p>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Description</h3>
        </div>
        <div class="panel-body">
            {{ lot.description }}
        </div>
    </div>

{% endblock content %}



{% block js %}
    {{ block.super }}
    <script src="{% static "js/bootstrap-lightbox.min.js" %}"></script>
    <script src="{% static "js/jquery.numeric.js" %}"></script>

    <script>
        pubnub.subscribe({
            channel: "{{ auction_channel }}",
            message: function (m) {
                $.bootstrapGrowl(m.text, {
                    offset: {from: 'top', amount: 60}, // 'top', or 'bottom'
                    delay: 30000
                });
                $('#current-bid-container').html(m.amount);
            },
            restore: true
        })

        $(".positive").numeric({ negative: false }, function() { alert("No negative values"); this.value = ""; this.focus(); });
    </script>
{% endblock js %}

templates/auctions/auction_edit.html
{% extends "base.html" %}
{% load staticfiles %}
{% load cloudinary %}
{% load crispy_forms_tags %}


{% block css %}
    {{ block.super }}
    <link href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" rel="stylesheet">
    <link href="{% static "css/jquery-ui-timepicker-addon.css" %}" rel="stylesheet">
{% endblock css %}


{% block navbar %}
    <ul class="nav navbar-nav">
        <li><a href={% url 'core:home' %}>Artworks</a></li>
        <li class="active"><a href={% url 'auctions:auction_list' %}>Auctions</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
        <li><a href={% url 'events:ping' %}>Ping</a></li>
    </ul>
    <div class="nav navbar-btn navbar-right btn-group">
        {% if user.is_authenticated %}
            <a class="btn btn-primary" href="{% url 'core:artwork_add' %}">Add Artwork</a>
            <a class="btn btn-default" href={% url 'profiles:logout' %}>Logout</a>
        {% else %}
            <a data-toggle="modal" href="#loginModal" class="btn btn-default">Log in</a>
            <a href="#" class="btn btn-default">Sign up</a>
        {% endif %}
    </div>
{% endblock navbar %}


{% block content %}
    <form role="form" action="{% url "auctions:auction_edit" slug=lot.slug %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Update</button>
        <a data-toggle="modal" href="#deleteModal" class="btn btn-danger">Delete</a>
    </form>
    {% include "includes/_auction_delete_confirmation.html" %}
{% endblock content %}


{% block js %}
    {{ block.super }}
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script src="{% static "js/jquery-ui-timepicker-addon.js" %}"></script>
    <script>
        $(function () {
            $("#id_start").datetimepicker({
                timeFormat: "HH:mm"
            });
            $("#id_end").datetimepicker({
                timeFormat: "HH:mm"
            });
        });
    </script>
{% endblock js %}

templates/auctions/auction_list.html
{% extends "base.html" %}
{% load cloudinary %}


{% block navbar %}
    <ul class="nav navbar-nav">
        <li><a href={% url 'core:home' %}>Artworks</a></li>
        <li class="active"><a href={% url 'auctions:auction_list' %}>Auctions</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
        <li><a href={% url 'events:ping' %}>Ping</a></li>
    </ul>
    <div class="nav navbar-btn navbar-right btn-group">
        {% if user.is_authenticated %}
            <a class="btn btn-primary" href="{% url 'core:artwork_add' %}">Add Artwork</a>
            <a class="btn btn-default" href={% url 'profiles:logout' %}>Logout</a>
        {% else %}
            <a data-toggle="modal" href="#loginModal" class="btn btn-default">Log in</a>
            <a href="#" class="btn btn-default">Sign up</a>
        {% endif %}
    </div>
{% endblock navbar %}


{% block content %}
    <div id="container">
        {% for auction in auction_list %}
            <div class="item">
                <a href="{{ auction.get_absolute_url }}">
                    {% cloudinary auction.lot.get_photo.image THUMBNAIL %}
                </a>
                <p>{{ auction.lot.title }} <span class="text-muted">by {{ auction.lot.artist }}</span></p>
                <p>
                    {% for tag in auction.lot.dehydrate_tags %}
                        <a href={% url 'auctions:tag_list' tag=tag %}><span class="badge">{{ tag }}</span></a>
                    {% endfor %}
                </p>
            </div>
        {% endfor %}
    </div>
    {% include "includes/_pagination.html" %}
{% endblock content %}


{% block js %}
    {{ block.super }}
    <script>
        var $container = $('#container');
        // initialize
        $container.masonry({
            columnWidth: 270,
            itemSelector: '.item',
            gutter: 15,
            isFitWidth: true,
            isInitLayout: false
        });

        // layout Masonry again after all images have loaded
        $container.imagesLoaded(function () {
            $container.masonry();
        });

        $container.infinitescroll(
                {
                    navSelector: ".pagination",
                    nextSelector: ".next",
                    itemSelector: ".item",
                    loading: {
                        finishedMsg: "",
                        img: "http://pathtoyour.com/loading.gif",
                        msg: null,
                        msgText: ""
                    }
                },
                function (newItems) {
                    var $newItems = $(newItems).css({"opacity": 0});
                    $newItems.imagesLoaded(function () {
                        $newItems.animate({"opacity": 1});
                        $container.masonry("appended", $newItems, true);
                    });
                }
        );
    </script>
{% endblock js %}