accounts/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', 'accounts.views.logout_user', name='logout'),
)

auctions/urls.py
from django.conf.urls import patterns, url

from .views import AuctionList, AuctionCreate, AuctionUpdate, AuctionDelete, AuctionDetail, BidView, AuctionTaggedList


urlpatterns = patterns('',
    url(r'auctions/$', AuctionList.as_view(), name='auction_list'),

    url(r'^auction/add/(?P<slug>[^\.]+)/$', AuctionCreate.as_view(), name='auction_add'),
    url(r'^auction/edit/(?P<slug>[^\.]+)/$', AuctionUpdate.as_view(), name='auction_edit'),
    url(r'^auction/delete/(?P<slug>[^\.]+)/$', AuctionDelete.as_view(), name='auction_delete'),

    url(r'^auction/bid/(?P<slug>[^\.]+)/$', BidView.as_view(), name='bid'),

    url(r'^auction/(?P<slug>[^\.]+)/$', AuctionDetail.as_view(), name='auction_detail'),

    url(r'^auctions/tag/(?P<tag>[^\.]+)/$', AuctionTaggedList.as_view(), name='tag_list'),
)

augeo/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from rest_framework import routers

from core.api import ArtworkViewSet
from auctions.api import AuctionViewSet

import core.urls as core
import auctions.urls as auctions
import social.apps.django_app.urls as social
import profiles.urls as profiles
import events.urls as events
import rest_framework.urls as rest_framework

admin.autodiscover()


# Routers provide an easy way of automatically determining the URL conf
router = routers.DefaultRouter()
router.register(r'artworks', ArtworkViewSet, base_name='artwork')
router.register(r'auctions', AuctionViewSet, base_name='auction')


urlpatterns = patterns('',
    url(r'^api/v1/', include(router.urls)),

    url(r'^admin/', include(admin.site.urls)),
    url(r'', include(core, namespace='core')),
    url(r'', include(auctions, namespace='auctions')),
    url('', include(social, namespace='social')),
    url(r'', include(profiles, namespace='profiles')),
    url(r'', include(events, namespace='events')),

    url(r'^api-auth/', include(rest_framework, namespace='rest_framework')),
    url(r'^api-token-auth/', 'rest_framework.authtoken.views.obtain_auth_token')
)

core/urls.py
from django.conf.urls import patterns, url

from .views import ArtworkList, ArtworkCreate, ArtworkUpdate, ArtworkDelete, ArtworkDetail, ContactFormView, ArtworkTaggedList

urlpatterns = patterns('',
    url(r'^$', ArtworkList.as_view(), name='home'),
    url(r'contact/$', ContactFormView.as_view(), name='contact'),
    url(r'artwork/add/$', ArtworkCreate.as_view(), name='artwork_add'),
    url(r'^artwork/edit/(?P<slug>[^\.]+)/$', ArtworkUpdate.as_view(), name='artwork_edit'),
    url(r'^artwork/delete/(?P<slug>[^\.]+)/$', ArtworkDelete.as_view(), name='artwork_delete'),
    url(r'^artwork/(?P<slug>[^\.]+)/$', ArtworkDetail.as_view(), name='artwork_detail'),
    url(r'^artworks/tag/(?P<tag>[^\.]+)/$', ArtworkTaggedList.as_view(), name='tag_list'),
)

events/urls.py
from django.conf.urls import patterns, url

from .views import ping

urlpatterns = patterns('',
    url(r'ping/$', ping, name='ping'),
)

core/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.core.cache import cache
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_delete, post_save
from django.dispatch import receiver

from cloudinary import api
from cloudinary.models import CloudinaryField
from rest_framework.authtoken.models import Token
from taggit.managers import TaggableManager
from uuslug import uuslug




@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)


for user in User.objects.all():
    Token.objects.get_or_create(user=user)


class ArtworkManager(models.Manager):
    def get_artwork(self, slug):
        key = "artwork:%s" % slug
        artwork = cache.get(key)
        if not artwork:
            artwork = Artwork.objects.select_related().get(slug=slug)
            if artwork:
                cache.add(key, artwork)
        return artwork


class Artwork(models.Model):
    title = models.CharField("Title", max_length=200, blank=False, db_index=True)
    slug = models.SlugField("Slug", max_length=50, blank=False, unique=True, db_index=True)
    artist = models.CharField("Artist", max_length=200, blank=True, db_index=True)
    description = models.TextField("Description", blank=True, null=True)
    publisher = models.ForeignKey(settings.AUTH_USER_MODEL, editable=False, db_index=True)
    published = models.DateTimeField("Published", auto_now_add=True)

    tags = TaggableManager("Tags", blank=True)

    objects = ArtworkManager()

    def save(self, *args, **kwargs):
        self.slug = uuslug(self.title, instance=self, max_length=50, word_boundary=True)
        super(Artwork, self).save(*args, **kwargs)
        key = "artwork:%s" % self.slug
        cache.set(key, self)

    def get_absolute_url(self):
        return reverse('core:artwork_detail', kwargs={'slug': self.slug})

    def get_photo(self):
        return Photo.objects.get_photo(self)

    def dehydrate_tags(self):
        return self.tags.names()

    def __unicode__(self):
        return "%s by %s" % (self.title, self.artist)


@receiver(pre_delete, sender=Artwork, dispatch_uid='artwork_pre_delete')
def artwork_pre_delete(sender, instance, using, **kwargs):
    key = "artwork:%s" % instance.slug
    cache.delete(key)




class PhotoManager(models.Manager):
    def get_photo(self, artwork):
        key = "photo:%s" % artwork.slug
        photo = cache.get(key)
        if not photo:
            photo = Photo.objects.get(artwork=artwork)
            if photo:
                cache.add(key, photo)
        return photo


class Photo(models.Model):
    caption = models.CharField("Caption", max_length=200, blank=True)
    image = CloudinaryField("Image", blank=True)
    artwork = models.ForeignKey(Artwork, on_delete=models.CASCADE, related_name='photos')

    objects = PhotoManager()

    def save(self, *args, **kwargs):
        super(Photo, self).save(*args, **kwargs)
        key = "photo:%s" % self.artwork.slug
        cache.set(key, self)

    def get_absolute_url(self):
        return self.image.url

    def __unicode__(self):
        try:
            result = self.image.public_id
        except AttributeError:
            result = ''
        return result


@receiver(pre_delete, sender=Photo, dispatch_uid='photo_pre_delete')
def photo_pre_delete(sender, instance, using, **kwargs):
    api.delete_resources([instance.image.public_id])

    key = "photo:%s" % instance.artwork.slug
    cache.delete(key)

core/forms.py
import floppyforms as forms
from cloudinary.forms import CloudinaryJsFileField

from .models import Photo, Artwork


class ArtworkForm(forms.ModelForm):
    class Meta:
        model = Artwork
        fields = ('title','artist','description','tags',)
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Title of the artwork'}),
            'artist': forms.TextInput(attrs={'placeholder': 'Artist name'}),
            'description': forms.Textarea,
        }


class PhotoForm(forms.ModelForm):
    image = CloudinaryJsFileField(
        attrs = { 'style': "display:none", 'id': "id_photo-image" },
        options={
            'tags': ["augeo", "photo"],
            'eager': [{'crop': 'fit', 'width': 240}]
        })

    class Meta:
        model = Photo
        fields = ('image',)


class ContactForm(forms.Form):

    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea)

core/views.py
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, DetailView, FormView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from braces.views import LoginRequiredMixin

from auctions.models import Auction
from .models import Artwork
from .forms import PhotoForm, ArtworkForm, ContactForm




class ArtworkList(ListView):
    paginate_by = 50

    def get_queryset(self):
        return Artwork.objects.all()


class ArtworkTaggedList(ListView):
    paginate_by = 50

    def get_queryset(self):
        tag = self.kwargs['tag']
        return Artwork.objects.filter(tags__name__in=[tag])


class ArtworkCreate(LoginRequiredMixin, CreateView):
    model = Artwork
    template_name = 'artwork_add.html'
    form_class = ArtworkForm

    def form_valid(self, form):
        form.instance.publisher = self.request.user
        context = self.get_context_data()
        photo_form = context['photo_form']
        if photo_form.is_valid():
            self.object = form.save()
            new_photo = photo_form.save(commit=False)
            new_photo.artwork = self.object
            new_photo.save()
            return HttpResponseRedirect(self.object.get_absolute_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

    def get_context_data(self, **kwargs):
        context = super(ArtworkCreate, self).get_context_data(**kwargs)
        if self.request.POST:
            context['photo_form'] = PhotoForm(self.request.POST, prefix='photo')
        else:
            context['photo_form'] = PhotoForm(prefix='photo')
        return context


class ArtworkDetail(DetailView):
    model = Artwork

    def get_object(self, queryset=None):
        artwork = Artwork.objects.get_artwork(self.kwargs['slug'])
        return artwork

    def get_context_data(self, **kwargs):
        context = super(ArtworkDetail, self).get_context_data(**kwargs)
        auction = Auction.objects.get_auction(self.object.slug)
        context['auction'] = auction
        return context


class ArtworkUpdate(LoginRequiredMixin, UpdateView):
    model = Artwork
    form_class = ArtworkForm
    template_name = 'artwork_edit.html'

    def get_object(self, queryset=None):
        artwork = Artwork.objects.get_artwork(self.kwargs['slug'])
        return artwork

    def get_success_url(self):
        return reverse_lazy('core:artwork_detail', kwargs={'slug': self.object.slug})


class ArtworkDelete(LoginRequiredMixin, DeleteView):
    model = Artwork
    success_url = reverse_lazy('core:home')




class ContactFormView(FormView):
    form_class = ContactForm
    template_name = "contact_form.html"
    success_url = reverse_lazy('core:home')

    def form_valid(self, form):
        message = "{name} / {email} said: ".format(
            name=form.cleaned_data.get('name'),
            email=form.cleaned_data.get('email'))
        message += form.cleaned_data.get('message')
        send_mail(
            subject=form.cleaned_data.get('subject').strip(),
            message=message,
            from_email='contact@augeo-cloud.herokuapp.com',
            recipient_list=['Anton Rau <anton.rau@gmail.com>'],
        )
        return super(ContactFormView, self).form_valid(form)

templates/core/artwork_add.html
{% extends "base.html" %}
{% load cloudinary %}
{% load crispy_forms_tags %}


{% block content %}
    <form role="form" action="{% url "core:artwork_add" %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form|crispy }}
        </div>
        <div class="form-group">
            {{ photo_form|crispy }}
            <button type="button" class="btn btn-default" onclick="$('input[id=id_photo-image]').click();">Upload Image</button>
        </div>
        <button type="submit" class="btn btn-primary">Add Artwork</button>
    </form>
    <div id="info"></div>
{% endblock content %}

{% block js %}
    {{ block.super }}
    <script>
        $('input[id=id_photo-image]').change(function() {
            $('#photoCover').val($(this).val());
        });

        $(document).ready(function () {
            // Cloudinary jQuery integration library uses jQuery File Upload widget
            // (see http://blueimp.github.io/jQuery-File-Upload/).
            // Any file input field with cloudinary-fileupload class is automatically
            // wrapped using the File Upload widget and configured for Cloudinary uploads.
            // You can further customize the configuration using .fileupload method
            // as we do below.
            $(".cloudinary-fileupload")
                    .fileupload({
                        // Uncomment the following lines to enable client side image resizing and valiation.
                        // Make sure cloudinary/processing is included the js file
                        //disableImageResize: false,
                        //imageMaxWidth: 800,
                        //imageMaxHeight: 600,
                        //acceptFileTypes: /(\.|\/)(gif|jpe?g|png|bmp|ico)$/i,
                        //maxFileSize: 20000000, // 20MB
                        dropZone: "#direct_upload",
                        start: function (e) {
                            $(".status").text("Starting upload...");
                        },
                        progress: function (e, data) {
                            $(".status").text("Uploading... " + Math.round((data.loaded * 100.0) / data.total) + "%");
                        },
                        fail: function (e, data) {
                            $(".status").text("Upload failed");
                        }
                    })
                    .off("cloudinarydone").on("cloudinarydone", function (e, data) {
                        $("#photo_bytes").val(data.result.bytes);
                        $(".status").text("");
                        $(".preview").html(
                                $.cloudinary.image(data.result.public_id, {
                                    format: data.result.format, width: 50, height: 50, crop: "fit"
                                })
                        );
                        view_upload_details(data.result);
                    });
        });

        function view_upload_details(upload) {
            // Build an html table out of the upload object
            var rows = [];
            $.each(upload, function (k, v) {
                rows.push(
                        $("<tr>")
                                .append($("<td>").text(k))
                                .append($("<td>").text(JSON.stringify(v))));
            });
            $("#info").html(
                    $("<div class=\"upload_details\">")
                            .append("<h2>Upload metadata:</h2>")
                            .append($("<table>").append(rows)));
        }
    </script>
{% endblock js %}

templates/core/artwork_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load cloudinary %}
{% load disqus_tags %}

{% disqus_dev %}


{% block css %}
    {{ block.super }}
    <link href="{% static "css/bootstrap-lightbox.min.css" %}" rel="stylesheet">
{% endblock css %}


{% block content %}
    <div class="page-header">
        <h1>
            <p>{{ artwork.title }}</p>
            <p><small>{{ artwork.artist }}</small></p>
        </h1>
    </div>


    {% with image=artwork.get_photo.image %}
        <div class="row">
            <div class="col-md-10">
                <a data-toggle="lightbox" href="#imageLightbox">
                    {% cloudinary image width=800 height=800 crop="fit" class="img-responsive img-rounded" %}
                </a>
            </div>
            <div class="col-md-2">

                {% if user.is_authenticated %}
                    {% if artwork.publisher == user %}
                        <div class="btn-group-vertical">
                            {% if auction %}
                                <a href="{% url 'auctions:auction_edit' slug=artwork.slug %}"
                                   class="btn btn-success"><span class="glyphicon glyphicon-usd"></span> Edit
                                    auction</a>
                            {% else %}
                                <a href="{% url 'auctions:auction_add' slug=artwork.slug %}"
                                   class="btn btn-success"><span class="glyphicon glyphicon-usd"></span> Put on
                                    auction</a>
                            {% endif %}
                            <a href="{% url 'core:artwork_edit' slug=artwork.slug %}" class="btn btn-warning"><span
                                    class="glyphicon glyphicon-edit"></span> Edit</a>
                            <a data-toggle="modal" href="#deleteModal" class="btn btn-danger"><span
                                    class="glyphicon glyphicon-trash"></span> Delete</a>
                        </div>
                        {% include "includes/_artwork_delete_confirmation.html" %}
                    {% endif %}
                {% endif %}
            </div>
        </div>

        <div id="imageLightbox" class="lightbox fade" tabindex="-1" role="dialog" aria-hidden="true">
            <div class='lightbox-dialog'>
                <div class='lightbox-content'>
                    {% cloudinary image %}
                    <div class='lightbox-caption'>
                        {{ artwork.title }}
                    </div>
                </div>
            </div>
        </div>
    {% endwith %}

    <p><small>Published {{ artwork.published|date }} by {{ artwork.publisher }}</small></p>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Description</h3>
        </div>
        <div class="panel-body">
            {{ artwork.description }}
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Comments</h3>
        </div>
        <div class="panel-body">
            {% disqus_show_comments %}
        </div>
    </div>
{% endblock content %}



{% block js %}
    {{ block.super }}
    <script src="{% static "js/bootstrap-lightbox.min.js" %}"></script>
{% endblock js %}

templates/core/artwork_edit.html
{% extends "base.html" %}
{% load cloudinary %}
{% load crispy_forms_tags %}

{% block content %}
    <form role="form" action="{% url "core:artwork_edit" slug=artwork.slug %}" method="post">
        {% csrf_token %}
        <div class="form-row">
            {{ form|crispy }}
        </div>
        <div class="form-row">
            {{ photo_form|crispy }}
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
    <div id="info"></div>
{% endblock content %}

{% block js %}
    {{ block.super }}
    <script>
        $(document).ready(function () {
            // Cloudinary jQuery integration library uses jQuery File Upload widget
            // (see http://blueimp.github.io/jQuery-File-Upload/).
            // Any file input field with cloudinary-fileupload class is automatically
            // wrapped using the File Upload widget and configured for Cloudinary uploads.
            // You can further customize the configuration using .fileupload method
            // as we do below.
            $(".cloudinary-fileupload")
                    .fileupload({
                        // Uncomment the following lines to enable client side image resizing and valiation.
                        // Make sure cloudinary/processing is included the js file
                        //disableImageResize: false,
                        //imageMaxWidth: 800,
                        //imageMaxHeight: 600,
                        //acceptFileTypes: /(\.|\/)(gif|jpe?g|png|bmp|ico)$/i,
                        //maxFileSize: 20000000, // 20MB
                        dropZone: "#direct_upload",
                        start: function (e) {
                            $(".status").text("Starting upload...");
                        },
                        progress: function (e, data) {
                            $(".status").text("Uploading... " + Math.round((data.loaded * 100.0) / data.total) + "%");
                        },
                        fail: function (e, data) {
                            $(".status").text("Upload failed");
                        }
                    })
                    .off("cloudinarydone").on("cloudinarydone", function (e, data) {
                        $("#photo_bytes").val(data.result.bytes);
                        $(".status").text("");
                        $(".preview").html(
                                $.cloudinary.image(data.result.public_id, {
                                    format: data.result.format, width: 50, height: 50, crop: "fit"
                                })
                        );
                        view_upload_details(data.result);
                    });
        });

        function view_upload_details(upload) {
            // Build an html table out of the upload object
            var rows = [];
            $.each(upload, function (k, v) {
                rows.push(
                        $("<tr>")
                                .append($("<td>").text(k))
                                .append($("<td>").text(JSON.stringify(v))));
            });
            $("#info").html(
                    $("<div class=\"upload_details\">")
                            .append("<h2>Upload metadata:</h2>")
                            .append($("<table>").append(rows)));
        }
    </script>
{% endblock js %}

templates/core/artwork_list.html
{% extends "base.html" %}
{% load cloudinary %}


{% block navbar %}
    <ul class="nav navbar-nav">
        <li class="active"><a href={% url 'core:home' %}>Artworks</a></li>
        <li><a href={% url 'auctions:auction_list' %}>Auctions</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="{% url 'core:contact' %}">Contact</a></li>
        <li><a href="{% url 'events:ping' %}">Ping</a></li>
    </ul>
    <div class="nav navbar-btn navbar-right btn-group">
        {% if user.is_authenticated %}
            <a class="btn btn-primary" href="{% url 'core:artwork_add' %}">Add Artwork</a>
            <a class="btn btn-default" href={% url 'profiles:logout' %}>Logout</a>
        {% else %}
            <a data-toggle="modal" href="#loginModal" class="btn btn-default">Log in</a>
            <a href="#" class="btn btn-default">Sign up</a>
        {% endif %}
    </div>
{% endblock navbar %}


{% block content %}
    <div id="container">
        {% for artwork in artwork_list %}
            <div class="item">
                <a href="{{ artwork.get_absolute_url }}">
                    {% cloudinary artwork.get_photo.image THUMBNAIL %}
                </a>
                <p>{{ artwork.title }} <span class="text-muted">by {{ artwork.artist }}</span></p>
                <p>
                    {% for tag in artwork.dehydrate_tags %}
                        <a href={% url 'core:tag_list' tag=tag %}><span class="badge">{{ tag }}</span></a>
                    {% endfor %}
                </p>
            </div>
        {% endfor %}
    </div>
    {% include "includes/_pagination.html" %}
{% endblock content %}


{% block js %}
    {{ block.super }}
    <script>
        var $container = $('#container');
        // initialize
        $container.masonry({
            columnWidth: 270,
            itemSelector: '.item',
            gutter: 15,
            isFitWidth: true,
            isInitLayout: false
        });

        // layout Masonry again after all images have loaded
        $container.imagesLoaded(function () {
            $container.masonry();
        });

        $container.infinitescroll(
                {
                    navSelector: ".pagination",
                    nextSelector: ".next",
                    itemSelector: ".item",
                    loading: {
                        finishedMsg: "",
                        img: "http://pathtoyour.com/loading.gif",
                        msg: null,
                        msgText: ""
                    }
                },
                function (newItems) {
                    var $newItems = $(newItems).css({"opacity": 0});
                    $newItems.imagesLoaded(function () {
                        $newItems.animate({"opacity": 1});
                        $container.masonry("appended", $newItems, true);
                    });
                }
        );
    </script>
{% endblock js %}

templates/core/artworks.html
{% extends "base.html" %}
{% load cloudinary %}

{% block content %}
    <div id="container">
        {% for artwork in artworks %}
            <div class="item">
                <a href="{{ photo.image.url }}" target="_blank">
                    {# Renders an IMG tag for a CloudinaryImage objects. #}
                    {# THUMBNAIL defined in context_processors #}
                    {% cloudinary photo.image THUMBNAIL %}
                    <p>{{ photo.image.public_id }} - {{ photo.title }}</p>
                </a>
            </div>
        {% endfor %}
    </div>
    {% include "_pagination.html" %}
{% endblock content %}

{% block js %}
    {{ block.super }}
    <script>
        var $container = $('#container');
        // initialize
        $container.masonry({
            columnWidth: 270,
            itemSelector: '.item',
            gutter: 15,
            isFitWidth: true,
            isInitLayout: false
        });

        // layout Masonry again after all images have loaded
        $container.imagesLoaded(function () {
            $container.masonry();
        });


        $container.infinitescroll(
                {
                    navSelector: ".pagination",
                    nextSelector: ".next",
                    itemSelector: ".item",
                    loading: {
                        finishedMsg: "",
                        img: "http://pathtoyour.com/loading.gif",
                        msg: null,
                        msgText: ""
                    }
                },
                function (newProducts) {
                    var $newProds = $(newProducts).css({"opacity": 0});
                    $newProds.imagesLoaded(function () {
                        $newProds.animate({"opacity": 1});
                        $container.masonry("appended", $newProds, true);
                    });
                }
        );


        function prettydump(obj) {
            ret = ""
            $.each(obj, function (key, value) {
                ret += "<tr><td>" + key + "</td><td>" + value + "</td></tr>";
            });
            return ret;
        }

        $(function () {
            $('#direct_upload input[type="file"]')
                    .fileupload({
                        dropZone: '#direct_upload',
                        start: function () {
                            $('.status_value').text('Starting direct upload...');
                        },
                        progress: function () {
                            $('.status_value').text('Uploading...');
                        }
                    })
                    .on('cloudinarydone', function (e, data) {
                        $('.status_value').text('Updating backend...');
                        $.post(this.form.action, $(this.form).serialize()).always(function (result, status, jqxhr) {
                            $('.status_value').text(result.errors ? JSON.stringify(result.errors) : status);
                        });
                        var info = $('<div class="uploaded_info"/>');
                        $(info).append($('<div class="data"/>').append(prettydump(data.result)));
                        $(info).append($('<div class="image"/>').append(
                                $.cloudinary.image(data.result.public_id, {
                                    format: data.result.format, width: 150, height: 150, crop: "fill"
                                })
                        ));
                        $('.uploaded_info_holder').append(info);
                    });
        });
    </script>
{% endblock js %}

templates/core/contact_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block navbar %}
    <ul class="nav navbar-nav">
        <li><a href={% url 'core:home' %}>Artworks</a></li>
        <li><a href={% url 'auctions:auction_list' %}>Auctions</a></li>
        <li><a href="#about">About</a></li>
        <li class="active"><a href="{% url 'core:contact' %}">Contact</a></li>
        <li><a href="{% url 'events:ping' %}">Ping</a></li>
    </ul>
    <div class="nav navbar-btn navbar-right btn-group">
        {% if user.is_authenticated %}
            <a class="btn btn-primary" href="{% url 'core:artwork_add' %}">Add Artwork</a>
            <a class="btn btn-default" href={% url 'profiles:logout' %}>Logout</a>
        {% else %}
            <a data-toggle="modal" href="#loginModal" class="btn btn-default">Log in</a>
            <a href="#" class="btn btn-default">Sign up</a>
        {% endif %}
    </div>
{% endblock navbar %}

{% block content %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form role="form" action="{% url "core:contact" %}" method="post">
                {% csrf_token %}
                <div class="form-row">
                    {{ form|crispy }}
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
{% endblock content %}