accounts/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', 'accounts.views.logout_user', name='logout'),
)

auctions/urls.py
from django.conf.urls import patterns, url

from .views import AuctionList, AuctionCreate, AuctionUpdate, AuctionDelete, AuctionDetail, BidView, AuctionTaggedList


urlpatterns = patterns('',
    url(r'auctions/$', AuctionList.as_view(), name='auction_list'),

    url(r'^auction/add/(?P<slug>[^\.]+)/$', AuctionCreate.as_view(), name='auction_add'),
    url(r'^auction/edit/(?P<slug>[^\.]+)/$', AuctionUpdate.as_view(), name='auction_edit'),
    url(r'^auction/delete/(?P<slug>[^\.]+)/$', AuctionDelete.as_view(), name='auction_delete'),

    url(r'^auction/bid/(?P<slug>[^\.]+)/$', BidView.as_view(), name='bid'),

    url(r'^auction/(?P<slug>[^\.]+)/$', AuctionDetail.as_view(), name='auction_detail'),

    url(r'^auctions/tag/(?P<tag>[^\.]+)/$', AuctionTaggedList.as_view(), name='tag_list'),
)

augeo/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from rest_framework import routers

from core.api import ArtworkViewSet
from auctions.api import AuctionViewSet

import core.urls as core
import auctions.urls as auctions
import social.apps.django_app.urls as social
import profiles.urls as profiles
import events.urls as events
import rest_framework.urls as rest_framework

admin.autodiscover()


# Routers provide an easy way of automatically determining the URL conf
router = routers.DefaultRouter()
router.register(r'artworks', ArtworkViewSet, base_name='artwork')
router.register(r'auctions', AuctionViewSet, base_name='auction')


urlpatterns = patterns('',
    url(r'^api/v1/', include(router.urls)),

    url(r'^admin/', include(admin.site.urls)),
    url(r'', include(core, namespace='core')),
    url(r'', include(auctions, namespace='auctions')),
    url('', include(social, namespace='social')),
    url(r'', include(profiles, namespace='profiles')),
    url(r'', include(events, namespace='events')),

    url(r'^api-auth/', include(rest_framework, namespace='rest_framework')),
    url(r'^api-token-auth/', 'rest_framework.authtoken.views.obtain_auth_token')
)

core/urls.py
from django.conf.urls import patterns, url

from .views import ArtworkList, ArtworkCreate, ArtworkUpdate, ArtworkDelete, ArtworkDetail, ContactFormView, ArtworkTaggedList

urlpatterns = patterns('',
    url(r'^$', ArtworkList.as_view(), name='home'),
    url(r'contact/$', ContactFormView.as_view(), name='contact'),
    url(r'artwork/add/$', ArtworkCreate.as_view(), name='artwork_add'),
    url(r'^artwork/edit/(?P<slug>[^\.]+)/$', ArtworkUpdate.as_view(), name='artwork_edit'),
    url(r'^artwork/delete/(?P<slug>[^\.]+)/$', ArtworkDelete.as_view(), name='artwork_delete'),
    url(r'^artwork/(?P<slug>[^\.]+)/$', ArtworkDetail.as_view(), name='artwork_detail'),
    url(r'^artworks/tag/(?P<tag>[^\.]+)/$', ArtworkTaggedList.as_view(), name='tag_list'),
)

templates/includes/_artwork_delete_confirmation.html
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Delete confirmation</h4>
            </div>
            <div class="modal-body">
                <p>You are about to delete current artwork. Do you want to proceed?</p>
            </div>
            <div class="modal-footer">
                <form role="form" action="{% url 'core:artwork_delete' slug=artwork.slug %}" method="post">
                    {% csrf_token %}
                    <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                    <button type="submit" class="btn btn-danger">Yes</button>
                </form>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div><!-- /.modal -->

templates/includes/_auction_delete_confirmation.html
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Delete confirmation</h4>
            </div>
            <div class="modal-body">
                <p>You are about to delete current auction. Do you want to proceed?</p>
            </div>
            <div class="modal-footer">
                <form role="form" action="{% url 'auctions:auction_delete' slug=auction.lot.slug %}" method="post">
                    {% csrf_token %}
                    <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                    <button type="submit" class="btn btn-danger">Yes</button>
                </form>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div><!-- /.modal -->

templates/includes/_bid_modal_form.html
<!-- Modal -->
<div class="modal fade" id="bidModal" tabindex="-1" role="dialog" aria-labelledby="bidModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Bid on Augeo</h4>
            </div>
            <div class="modal-body">
                <form role="form" action="{% url "auctions:bid" slug=lot.slug %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="amount">Amount</label>
                        <input name="amount" id="amount" type="text" class="form-control positive" placeholder="{{ bid }}" autofocus>
                    </div>
                    <button type="submit" class="btn btn-default">Bid</button>
                </form>
            </div>
            <div class="modal-footer">
                {{ lot.title }}
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div><!-- /.modal -->

templates/includes/_footer.html
<div id="footer">
    <div class="container">
        <p class="text-muted credit">Created by <a href="http://rau.ru">Anton Rau</a>.</p>
    </div>
</div>

templates/includes/_login_modal_form.html
<!-- Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Please login</h4>
            </div>
            <div class="modal-body">
                <form role="form" action="{% url "profiles:login" %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="username">Name</label>
                        <input name="username" id="username" type="text" class="form-control" placeholder="Name"
                               required autofocus>
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input name="password" id="password" type="password" class="form-control"
                               required placeholder="Password">
                    </div>
                    <button type="submit" class="btn btn-default">Log in</button>
                </form>
            </div>
            <div class="modal-footer">
                <a href="{% url 'social:begin' "facebook" %}" class="btn btn-facebook"><i class="icon-facebook"></i> | Connect with Facebook</a>
                <a href="{% url 'social:begin' "twitter" %}" class="btn btn-twitter"><i class="icon-twitter"></i> | Connect with Twitter</a>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div><!-- /.modal -->

templates/includes/_pagination.html
<ul class="pagination">
    {% if page_obj.has_previous %}
        <li><a href="?{{ page_obj.previous_page_number.querystring }}" class="prev">&laquo;</a></li>
    {% else %}
        <li class="disabled">&laquo;</li>
    {% endif %}

    {% for page in page_obj.pages %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <li class="active">{{ page }}</li>
            {% else %}
                <li><a href="?{{ page.querystring }}">{{ page }}</a></li>
            {% endifequal %}
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <li><a href="?{{ page_obj.next_page_number.querystring }}" class="next">&raquo;</a></li>
    {% else %}
        <li class="disabled">&raquo;</li>
    {% endif %}
</ul>

templates/includes/_scripts.html
{% load cloudinary %}
{% load staticfiles %}

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src=http://cdn.pubnub.com/pubnub-3.5.43.min.js></script>
<script src="{% static "js/jquery.infinitescroll.min.js" %}"></script>
<script src="{% static "js/jquery.bootstrap-growl.min.js" %}"></script>
<script src="{% static "js/imagesloaded.pkgd.min.js" %}"></script>
<script src="{% static "js/masonry.pkgd.min.js" %}"></script>

{% cloudinary_includes %}
{% cloudinary_js_config %}

{% if user.is_authenticated %}
    <script>
        // Init
        var pubnub = PUBNUB.init({
            subscribe_key: 'sub-c-40f49aaa-2c51-11e3-80e9-02ee2ddab7fe'
        })

        // LISTEN
        pubnub.subscribe({
            channel: "{{ user.username }}",
            message: function (m) {
                $.bootstrapGrowl(m.text, {
                    offset: {from: 'top', amount: 60}, // 'top', or 'bottom'
                    delay: 30000
                });
            },
            restore: true
        })
    </script>
{% endif %}